### ISSUE TITLE
Popup dimensions doesn't match setting / Invisible borders in Windows 10

### ISSUE THREAD

**Issue by aqt** [aqt/webext-popup#10]
Windows 10 has **invisible borders** on the left, bottom, and right. These borders _appear_ to be 1px wide, but there are 7 invisible pixels. Borders are actually 8px wide.

This means you need to add 14px to the width and 7px to the height.

This is a flaw in Windows APIs, but they appear to have made no effort in fixing it.

As far as I know there's no web extension API to get this sort of information. We could _guess_ based on operative system, but since there are so many different flavors and the size is still customizable I don't believe it would be a good option.

**Comment by aqt** [comment]
@maverick74 This issue is about a Windows quirk with border sizing, it's not relevant to your question.
I assume you're asking due to #13? I have replied with my thoughts there.

**Comment by maverick74** [comment]
Actually i was really referring to this issue because i did noticed this same "quirk" (that looks bad) but thought it was a FF problem. So, my question was if there is no way around this thru FF. I guess you answered that on #13 already.
Thanks

**Comment by aqt** [comment]
@maverick74 Ah I see, my bad!
Unfortunately there is no solution for this issue yet and sadly I doubt there will be, at least not in the near future. Either Microsoft needs to fix their Windows API or Mozilla need to adjust their API for this edge case.

As a sidenote, it is possible to calculate the border sizes, but that includes the invisible pixels: `window.outerWidth - window.innerWidth`

**Comment by aqt** [comment]
The issue will persist for the forseeable future, so I've added an optional workaround.

**Comment by mirh** [comment]
We talking about [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1531058) maybe? 
Left, bottom, and right are actually 100% legit on the last firefox and w10.

**Comment by aqt** [comment]
@mirh No that is a separate issue. I have updated this issue description with an example image (since I had already created it to explain this before).
