### ISSUE TITLE
Restoration of a popped-up tab, to a window: wording

### ISSUE THREAD

**Issue by grahamperrin** [aqt/webext-popup#14]
Building upon #4 

For a while, I stopped using the extension because (in the absence of a PopUp feature in the popped-up tab) I couldn't figure out how to get a popped-up tab back to the window where it originated. 

(I had weird workarounds, something like … close the popped-up window, and then use the History menu of the original window to reopen the closed tab.)

----

Eventually I realised, a problem (for me) with the wording.

> Restore to tab…

– could be worded more accurately,

> Restore to window …

or

> Restore tab …

Thanks!

Also, I realised that restoration can be to _any_ window that shows the PopUp icon (not only its original window).

**Comment by aqt** [comment]
I agree the wording is a bit odd. Changing it to `Restore to this window` would make it more clear.
