### ISSUE TITLE
Preset urls

### ISSUE THREAD

**Issue by rayman89** [aqt/webext-popup#17]
Could you make the addon able to put sites like in a favorite list and make a button functionality be that when you click it would display the favorite list and clicking on any of those sites would open them in a popup?

**Comment by aqt** [comment]
I will not be adding this, it doesn't add much value compared to using a bookmarks folder.

However, I can definitely add a context menu item for bookmarks, to open a bookmark as a popup. This was not possible before Firefox 59 (3 months ago) so I didn't know it was added.

Would adding that function be sufficient for your needs?

**Comment by aqt** [comment]
I have released a new version (1.3.3) that adds the popup function to bookmark context menus.

**Comment by rayman89** [comment]
It does not work for what I had planned. The idea was to have stuff quickly at hand and make 1 or 2 clicks to get to it. Specially I wanna open about:downloads in a popup and have that at hand. 

BTW the changes you made do not apply to control + b (bookmarks sidebar) and control + shift + B (bookmark manager)

**Comment by aqt** [comment]
Unfortunately I don't have a solution for you then.

Yes, that issue is with Firefox. They do not add the item to those menus yet. I found this relevant issue on their issue tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1419195
