### ISSUE TITLE
[Suggestions] 1. Pop-up window position 2. Auto pop-up URL

### ISSUE THREAD

**Issue by berlihingen** [aqt/webext-popup#26]
1. It looks mandatory: if I have to move pop-up manually (to use windows in parallel) I can create it the same way by dragging out the tab. So, the basics for default position (top-left, top-right, bottom-left, bottom-right) would be enough.
2. Again - maybe it's just my workflow - but domains auto pop-up doesn't help much, it would be great to white-list particular document full address.

**Comment by aqt** [comment]
1. Not sure I understood this request, do you want to add x/y position to the rules? I wanted to add this but it was not working correctly at the time, I'll take another look at it.
2. Support for matching entire URL is planned, see #23

**Comment by berlihingen** [comment]
1. Correct. TBH for me personally x=0 and y=0 would be enough, as I rarely work more than with 2 windows.
2. That's great :)
Thanks for answering.

**Comment by aqt** [comment]
I have released a new version with your first suggestion. I'll refer to the other issue regarding your second suggestion, and close this issue.

**Comment by aqt** [comment]
Just a note if you haven't noticed issue #10: If you use Windows 10 there are invisible borders around the windows and you need to adjust accordingly.
For example to place a window at x=0 and y=0 you need to actually set x=-7 and y=0.
