### ISSUE TITLE
Preference to not show the URL in the title bar

### ISSUE THREAD

**Issue by grahamperrin** [aqt/webext-popup#27]
Enhancement request: please, can you add a preference to not show the URL? 

I rely heavily on visibility of titles. Prefer the true title of a page, nothing more.

**Comment by aqt** [comment]
I cannot do anything about it unfortunately, it is added automatically and without option to remove it.
I found a [bug on bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1296365) about it and will have to refer you to it for more information.
