### ISSUE TITLE
1.3.6: restored tab lacks its title (misrepresented as New Tab) with Waterfox 56.2.3

### ISSUE THREAD

**Issue by grahamperrin** [aqt/webext-popup#28]
For example, with just one window, after popping out then restoring: 

![2018-09-22 20 59 56 waterfox](https://user-images.githubusercontent.com/192271/45921296-d447e780-beaa-11e8-9280-22bba0019015.png)

**Comment by aqt** [comment]
Yes I noticed this previously and decided not to fix it, see #5. I didn't think of Firefox forks at the time though so I think it's worth fixing now.

**Comment by grahamperrin** [comment]
Oh sorry, I looked for a duplicate before opening this. Word blindness today.
