### ISSUE TITLE
Popup Title has URL first

### ISSUE THREAD

**Issue by maverick74** [aqt/webext-popup#33]
When we create a Popup in the titlebar it shows "URL - PageTitle" however i believe it would be better if it would have "PageTitle - URL" for better identification on the taskbar

**Comment by aqt** [comment]
I'm closing this as a duplicate of #27.

This is a feature in Firefox to help prevent phishing and unfortunately cannot be turned off.
I can only recommend you voice your opinion in the bugzilla bug linked in the issue above.
