### ISSUE TITLE
PopUp 1.4.0 compatibilty with Waterfox

### ISSUE THREAD

**Issue by grahamperrin** [aqt/webext-popup#36]
1.3.7 works with Waterfox 56.2.6, 1.4.0 does not. There's the menu option to pop up, but the pop does not occur.

**Comment by aqt** [comment]
Sorry about that, a bug snuck in in the settings migration phase. I have submitted version 1.4.1 to address this and an issue with page context menus.

**Comment by aqt** [comment]
Just fixed another bug I noticed, causing restore to fail if the popup is the only window open. I'll submit a new version shortly.

**Comment by grahamperrin** [comment]
Thanks. 1.4.2 seems to be bugged in the same way …

**Comment by aqt** [comment]
Hmm... I cannot reproduce this. Would you mind looking at the debug logs (about:debugging) and see if you get an error from the extension?
Aside from `Error: Type error for parameter updateProperties (Unexpected property "visible") for contextMenus.update.` - it is expected, harmless and can be ignored

**Comment by grahamperrin** [comment]
Hmm, now (after the same update from 1.3.7 to 1.4.2) it seems to be OK. I'll continue testing.

**Comment by grahamperrin** [comment]
Sorry for the late follow up. 

1.4.2 does seem to work as expected. Thanks!
