### ISSUE TITLE
Request - I want to adjust the title of the popup window

### ISSUE THREAD

**Issue by aviscaerulea** [aqt/webext-popup#38]
I open multiple popups in the same domain. However, when selecting a popup on the Windows taskbar, it is difficult to determine because most of the window titles are URLs.

I want the page name to be the title of the popup window by setting.
I would like such an option.

**Comment by aqt** [comment]
Is this related to issue #27, or a feature request to change the _title of a page_ which comes after the URL?

**Comment by aviscaerulea** [comment]
Oh ..., sorry, my request was the same as issue # 27.
Please close it as a duplicate.
