### ISSUE TITLE
Maximize button is disabled

### ISSUE THREAD

**Issue by renaatdemuynck** [aqt/webext-popup#47]
Hi, the maximize button of the pop-up is always disabled. Is it possible to enable it?

**Comment by aqt** [comment]
Hey, I'm guessing you're on Windows where this is a known issue. Unfortunately it's not possible as it's a limitation in Firefox.

There are some suggestions in issue #13 on ways to work around it. Either by using the [popup position rules](https://github.com/aqt/webext-popup/issues/13#issuecomment-438704298) or [using a bug](https://github.com/aqt/webext-popup/issues/13#issuecomment-774024131) to enable Windows aero snap.
