### ISSUE TITLE
Tab title is incorrect after restoring

### ISSUE THREAD

**Issue by aqt** [aqt/webext-popup#5]

**Comment by aqt** [comment]
Might have been a problem with 56.0.2. As of 57.0 I'm no longer seeing this error.

**Comment by aqt** [comment]
Closing this as I've not seen the bug appear again

**Comment by aqt** [comment]
That extension is using the old system, same methods cannot be used by webextensions unfortunately.

It might be too hard to try to fix the problem with the limited API:

Unfortunately the tab update function [doesn't include](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update) a way to set titles.
I could in theory use `tabs.executeScript` to run `document.title="oldTitle"` but it is complaining about permissions despite having them.

---

There is a way to fix it by dragging the tab into a new window which will restore the title, then drag it back to the other window.
I don't really want to add a fix to do this automatically though since it would look sketchy with a window suddenly opening and closing.

**Comment by aqt** [comment]
I misread what you wrote. Perhaps it works with that addon since it changes the way tabs work, but it doesn't help the situation.

**Comment by grahamperrin** [comment]
Thanks, no worries. 

> Might have been a problem with firefox version 56.0.2. …

OK, that's consistent with (last year's) initial release of Waterfox 56 (56.0) based on Firefox 56.0.2. 

If I'm the _only_ person observing this issue, don't attempt to fix it for me alone. I do normally use Vertical Tabs Reloaded (VTR) so for me personally this #5 is a non-issue.

**Comment by aqt** [comment]
I will close this as wontfix since it's a relatively minor bug, has an in my opinion acceptable workaround and has been fixed in later versions of Firefox.
