### ISSUE TITLE
Auto-popup does not work when specifying a port

### ISSUE THREAD

**Issue by RedMser** [aqt/webext-popup#50]
Thanks for your work on this extension!

Auto-popup works fine when entering `localhost` as domain, even if I open a tab that specifies a port in the address bar.
But in the settings, neither when using domain nor URL as the matching mode, can I specify a specific port to filter by, like `localhost:1234` does not auto-popup. This also does not work when using an IP address such as `127.0.0.1:1234` in the settings instead.

**Comment by aqt** [comment]
I have added the port in domain mode, a new version will be available shortly.

The search pattern is matched against the whole domain/URL, which is likely why URL did not work for you. With an URL pattern, going to `localhost:1234` would be matching the pattern against `http:/localhost:1234/`. For your use case you could use wildcards in that mode: `*localhost:1234*` or `/.*localhost:1234.*/` (RegExp).

**Comment by RedMser** [comment]
Thanks you so much, that fixed the issue for me in domain mode :)

Regarding URL mode, it was a bit confusing to me because
- the examples in the tooltip only mentioned domain mode (so no protocol was included)
- the URL in firefox's address bar does not include the http:// for localhost
but it did end up working if I enter the URL fully, or use wildcards.

So maybe including a hint in the tooltip about what the search string for URL typically looks like would help a lot for new users. Or maybe it's just confusing specifically for the localhost case, which hides the protocol, but intuitive enough otherwise...
I'll let you be the judge of that.

**Comment by aqt** [comment]
I agree it's confusing, even I misremembered and thought it should be doing a partial match rather than full. I'll see what I can do about clarifying these details and providing URL examples, I don't want to overcrowd the tooltip but I don't really want to do a large re-design the settings page either.
