### ISSUE TITLE
Window is Always on top by default

### ISSUE THREAD

**Issue by tiekookeit** [aqt/webext-popup#51]
Hi, ty for this addon anyway, but I am on a linux box running debian 11 with xfce4 and every time I try to popup a windows, the window is always stay on top and I cant bring firefox main windows to front, I have to manualy minimize the popup windows to get back to main firefox windows. Is that right? Is that the intended behavior? I tried to search for some way to fix it but I just cant change that...  By the way, it is not on top of other windows, just on top of firefox main window... is there a way to switch using alt+tab between firefox main windows and the popup window?

**Comment by aqt** [comment]
Hi, no this is not expected, popups should behave the same as any other window.
Unfortunately the cause of these problems shouldn't be this extension - There are no APIs to effect such behavior.

I don't have much experience in this area but I think the problem would likely either be in what properties Firefox assigns the popup window, or how your window manager (xfwm4?) handles those properties. The problems sound like `_NET_WM_STATE_MODAL` or `_NET_WM_STATE_ABOVE`. You can use `xprop` to list properties. If that's the issue maybe there's a way to configure how your window manager handles them.
